"""Application-wide constants (roles, permissions).

Kept in one place so role strings are never hardcoded across the codebase.
Roles mirror doc 04 - User Roles.
"""


class Roles:
    EMPLOYEE = 'employee'
    MANAGER = 'manager'
    ANALYST = 'analyst'          # "Security Analyst" in the docs
    ADMIN = 'admin'              # "System Administrator" in the docs

    ALL = (EMPLOYEE, MANAGER, ANALYST, ADMIN)


# Roles permitted to use the Security Dashboard, AI alerts and security
# analytics (doc 04 permission matrix). Everyone else is workspace-only.
SECURITY_ROLES = (Roles.ANALYST, Roles.ADMIN)

# Roles permitted to use the Workspace (projects/tasks/files/notes/chat).
# Security Analysts are security-only and do not touch business data (doc 04).
WORKSPACE_ROLES = (Roles.EMPLOYEE, Roles.MANAGER, Roles.ADMIN)


class AlertStatus:
    """Lifecycle of an AI-raised alert (the container an analyst works from)."""
    OPEN = 'open'                 # raised by the AI, not yet acted on
    INVESTIGATING = 'investigating'
    CLOSED = 'closed'
    ALL = (OPEN, INVESTIGATING, CLOSED)


class InvestigationState:
    """Analyst-driven workflow states (constitution: the analyst decides).

    Confirming a threat does not end the case — it opens the incident-response
    phase (Confirmed -> Containing -> Resolved), mirroring a real SOC workflow.
    Only False Positive (no threat) and Closed (archived) are terminal.
    """
    OPEN = 'open'
    ASSIGNED = 'assigned'
    INVESTIGATING = 'investigating'
    NEEDS_EVIDENCE = 'needs_evidence'
    FALSE_POSITIVE = 'false_positive'   # terminal — analyst's verdict, no threat
    CONFIRMED = 'confirmed'             # verdict: real threat — response begins
    CONTAINING = 'containing'           # active containment / remediation
    RESOLVED = 'resolved'               # response complete, ready to archive
    CLOSED = 'closed'                   # terminal — archived with full audit trail
    ALL = (OPEN, ASSIGNED, INVESTIGATING, NEEDS_EVIDENCE, FALSE_POSITIVE,
           CONFIRMED, CONTAINING, RESOLVED, CLOSED)
    TERMINAL = (FALSE_POSITIVE, CLOSED)
    # States reached only after a real threat was confirmed — the incident
    # response phase of the workflow.
    RESPONSE_PHASE = (CONFIRMED, CONTAINING, RESOLVED)


class IncidentSeverity:
    """Analyst-assigned incident severity — distinct from the AI's alert
    severity (suspicious/critical). The AI flags anomalies; only a human
    assigns how serious the confirmed incident actually is."""
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    CRITICAL = 'critical'
    ALL = (LOW, MEDIUM, HIGH, CRITICAL)


class IncidentActionType:
    """What kind of entry appears in an incident's audit trail."""
    CONTAINMENT = 'containment'
    REMEDIATION = 'remediation'
    ESCALATION = 'escalation'
    EVIDENCE = 'evidence'
    NOTE = 'note'
    STATUS_CHANGE = 'status_change'
    ALL = (CONTAINMENT, REMEDIATION, ESCALATION, EVIDENCE, NOTE, STATUS_CHANGE)
    # Types an analyst can log directly via the generic "add action" endpoint —
    # escalation/evidence/status_change are always system-generated by their
    # own dedicated endpoints so the audit trail can't be spoofed.
    ANALYST_LOGGABLE = (CONTAINMENT, REMEDIATION, NOTE)


# Severities an anomaly can carry into an Alert (mirrors event.status).
ALERT_SEVERITIES = ('suspicious', 'critical')
