"""Request schemas for the incident-response workflow (post-confirmation)."""
from typing import Optional

from pydantic import BaseModel, Field


class InvestigationTransition(BaseModel):
    state: str
    notes: Optional[str] = Field(default=None, max_length=5000)
    resolution_summary: Optional[str] = Field(default=None, max_length=5000)


class SeverityUpdate(BaseModel):
    severity: str = Field(pattern=r'^(low|medium|high|critical)$')


class EscalateRequest(BaseModel):
    to_user_id: int
    note: Optional[str] = Field(default=None, max_length=1000)


class IncidentActionCreate(BaseModel):
    # Escalation/evidence/status-change are system-generated by their own
    # endpoints — an analyst can only log these three kinds directly.
    action_type: str = Field(pattern=r'^(containment|remediation|note)$')
    description: str = Field(min_length=1, max_length=2000)
