"""index events hot columns

Revision ID: 29af6613babb
Revises: 06dc5dd045f9
Create Date: 2026-07-24 20:18:25.804344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29af6613babb'
down_revision = '06dc5dd045f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    # ### end Alembic commands ###
