"""add bio and avatar_path to users

Revision ID: 413f4ed4b63c
Revises: aebb4311a80e
Create Date: 2026-07-25 13:27:39.502143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413f4ed4b63c'
down_revision = 'aebb4311a80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
