"""add incident response workflow

Revision ID: b53c0ee628e6
Revises: 8bbbd77927a9
Create Date: 2026-07-25 15:23:59.293235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53c0ee628e6'
down_revision = '8bbbd77927a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_actions_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('incident_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_evidence_investigation_id'), ['investigation_id'], unique=False)

    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('resolution_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('escalated_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('escalated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('escalation_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_investigations_escalated_to_id_users',
                                    'users', ['escalated_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_investigations_escalated_to_id_users', type_='foreignkey')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('escalation_note')
        batch_op.drop_column('escalated_at')
        batch_op.drop_column('escalated_to_id')
        batch_op.drop_column('resolution_summary')
        batch_op.drop_column('severity')

    with op.batch_alter_table('incident_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_evidence_investigation_id'))

    op.drop_table('incident_evidence')
    with op.batch_alter_table('incident_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_actions_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_incident_actions_created_at'))

    op.drop_table('incident_actions')
    # ### end Alembic commands ###
