"""add alerts, investigations, risk_scores

Revision ID: f213cefe9a15
Revises: 0f760b9b87d9
Create Date: 2026-07-24 12:03:09.632949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f213cefe9a15'
down_revision = '0f760b9b87d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('open_alerts', sa.Integer(), nullable=False),
    sa.Column('last_flagged_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_scores_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_user_id'), ['user_id'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ai_analysis_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_analysis_id'], ['ai_analyses.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_alerts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_analyst_id'), ['analyst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_analyst_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_alert_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_event_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_scores_organization_id'))

    op.drop_table('risk_scores')
    # ### end Alembic commands ###
